# Site settings
title: LilyMandarin | Leçons de chinois à Bordeaux
appname: LilyMandarin
description: >
  Le chinois, une langue d’avenir. Pro : boostez votre performance professionnelle. Parents :
  développez le potentiel de votre enfant.

url: "http://lilymandarin.com"

# Build settings
markdown: redcarpet
permalink: pretty
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - watch
  - npm-debug.log
defaults:
  -
    values:
      layout: null
