# Site settings
title: Cours de chinois à Bordeaux
appname: LilyMandarin
description: >-
    Le chinois, une langue d'avenir. Pros : boostez votre performance professionnelle. Parents :
    développez le potentiel de votre enfant.
url: "https://lilymandarin.com"

# Build settings
markdown: redcarpet
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - watch
  - npm-debug.log
  - node_modules
  - gulpfile.js
  - package.json
  - dist
defaults:
  -
    values:
      layout: null
